pipeline:
  # Build
  build:
    image: google/dart:${DART_VERSION}
    pull: true
    commands:
      - sh build.sh
    environment:
      - DARTANALYZER_FLAGS=--fatal-warnings

  # Code coverage
  coverage:
    image: plugins/coverage
    server: https://aircover.co
    pattern: lcov.info
    when:
      matrix:
        DART_VERSION: dev

# Matrix
matrix:
  DART_VERSION:
    - latest
    - dev
