name: dogma_source_metadata_test
version: 0.1.0
description: Metadata testing for the Dogma libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io

environment:
  sdk: '>=1.21.0-any <2.0.0'

dependencies:
  dogma_source_metadata:
    path: ../dogma-source-metadata
  test: ^0.12.15
  meta: ^1.0.0
